name: Production CD (Continuous Deployment)

on:
  pull_request:
    branches: ["main"]
    types: [closed]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  version-bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git config
        run: |
          git config --local user.name "boutzi"
          git config --local user.email "joe@arkaans.com"

      - name: Increment version (package.json)
        id: increment_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"

          PR_TITLE="${{ github.event.pull_request.title }}"

          if [[ "$PR_TITLE" == *"major"* ]]; then
              major=$((major + 1))
              minor=0
              patch=0
          elif [[ "$PR_TITLE" == *"feat"* ]]; then
              minor=$((minor + 1))
              patch=0
          elif [[ "$PR_TITLE" == *"fix"* ]]; then
              patch=$((patch + 1))
          else
              echo "No version keyword found. Skipping bump."
              exit 0
          fi

          NEW_VERSION="$major.$minor.$patch"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp.$$.json && mv tmp.$$.json package.json

      - name: Commit and push version bump to main
        run: |
          git add package.json
          git diff --staged --quiet && echo "Nothing to commit" && exit 0
          git commit -m "chore: bump version to ${{ env.new_version }}"
          git push origin main

      - name: Sync dev with main
        run: |
          git checkout dev
          git pull origin dev
          git merge main --no-edit
          git push origin dev
